on:
  pull_request:
    branches:
      - 'master'
  push:
    branches:
      - 'master'
      
jobs:
   steps:
   - name: Setup Java JDK
     uses: actions/setup-java@v2.1.0
   - uses: actions/checkout@v2
   - uses: actions/setup-java@v2
     with:
       distribution: 'adopt'
       java-version: '11'
       check-latest: true
   - run: java -cp java TestBo
   -name: Ocultar Token
   env:
      BOT_TOKEN: ${{secrets.BOT_TOKEN}}t
